# Generated by Django 4.2.16 on 2024-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_alter_buyer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
