# Generated by Django 4.2.17 on 2024-12-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='сontent',
            new_name='content',
        ),
    ]
